### ISSUE TITLE
Be on the Powered by Faust page?

### ISSUE THREAD

**Issue by sletz** [SpotlightKid/dfzitarev1#1]
Would you be interested to be added on the [Powered by Faust page](https://faust.grame.fr/community/made-with-faust/) ? If yes do you have a nice screenshot to share?

**Comment by SpotlightKid** [comment]
I added a screenshot of the generic LV2 plugin UI in Ardour6 to the repo:

https://github.com/SpotlightKid/dfzitarev1/blob/master/screenshot-ardour6.png

Please note that this project does not have an official release yet, since I built this mainly for my own benefit. But I'll try to make one soon.

You might also want to include these repos on the page:

* https://github.com/SpotlightKid/faustfilters
* https://github.com/SpotlightKid/sendmixer
* https://github.com/SpotlightKid/stereocrossdelay

I will add screenshots to those, if they do not have one yet, as soon as I can.

**Comment by sletz** [comment]
Done [here](https://faust.grame.fr/community/made-with-faust/#df-zita-rev1), thanks.

**Comment by SpotlightKid** [comment]
This project now has its [first official release](https://github.com/SpotlightKid/dfzitarev1/releases/tag/v0.1.0).
